name: terraform-apply

on:
  push:
    branches: [main]
    paths:
      - "shared/**"
      - "environments/**"
      - "modules/**"
      - ".github/workflows/terraform-apply.yml"
  workflow_dispatch:
    inputs:
      stack:
        description: "Which stack to apply"
        required: true
        type: choice
        options:
          - shared
          - environments/dev
          - environments/prod

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  TF_VERSION: "1.7.5"

jobs:
  apply-shared-and-dev:
    name: apply (${{ matrix.stack }})
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        stack: [shared, environments/dev]
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::REPLACE_ACCOUNT_ID:role/member-mitra-infra-dev
          aws-region: ${{ env.AWS_REGION }}

      - name: terraform init
        working-directory: ${{ matrix.stack }}
        run: terraform init -input=false

      - name: terraform apply
        working-directory: ${{ matrix.stack }}
        run: terraform apply -auto-approve -input=false

  apply-prod:
    name: apply prod (manual)
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && inputs.stack == 'environments/prod'
    environment: production # GitHub Environment with required reviewers.
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::REPLACE_ACCOUNT_ID:role/member-mitra-infra-prod
          aws-region: ${{ env.AWS_REGION }}

      - name: terraform init
        working-directory: environments/prod
        run: terraform init -input=false

      - name: terraform apply
        working-directory: environments/prod
        run: terraform apply -auto-approve -input=false
